apiVersion: v1
entries:
  flotorch:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-04-15T18:23:50.488666+05:30"
    description: A Helm chart for Flotorch Enterprise
    digest: 057b90c9d7b17df41df2355bd152fd66c03be6bb450b338d7b76edbdf1e8cd8b
    name: flotorch
    type: application
    urls:
    - https://balasriharsha-ch.github.io/FloTorch/charts/flotorch-0.1.0.tgz
    version: 0.1.0
generated: "2025-04-15T18:23:50.4877+05:30"
